################################################################################
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: OTHER
# SPDX-FileCopyrightText: (c) 2021-2022, The Raetro authors and contributors
################################################################################
name: Test Build
################################################################################
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
################################################################################
jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: raetro/quartus:17.0
    ############################################################################
    steps:
      ##########################################################################
      # 1 - Checkout repository
      ##########################################################################
      - name: Checkout repository
        uses: actions/checkout@v2
      ##########################################################################
      # 2 - RTL synthesis
      ##########################################################################
      - name: Run compilation flow
        run: quartus_sh --flow compile Arcade-XSleenaCore.qpf
        
        # 5 - Get current version for tagging
      - name: Get the version
        id: version
        run: echo "::set-output name=version::$(date +'%Y%m%d')"
        
        # 6 - Copy Artifacts
      - name: Create a copy and tag with version
        run: |
          mkdir -p release
          cp project/output_files/Arcade-XSleenaCore.rbf releases/Arcade-XSleenaCore_${{ steps.version.outputs.version }}.rbf
          cp project/output_files/Arcade-XSleenaCore.fit.summary releases/Arcade-XSleenaCore.fit_${{ steps.version.outputs.version }}.txt
          
      ##########################################################################
      # 3 - Upload artifacts
      ##########################################################################
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Arcade-XSleenaCore_${{ steps.version.outputs.version }}
          path: releases/
